#!/usr/bin/env bash

set -euo pipefail

nix show-derivation "$(nix-instantiate --add-root drv.root)" | jq

nix-hash --type sha256 myfile
nix-store --dump myfile | tee myfile.dump | sha256sum
nix-store --dump myfile | tee myfile.dump | sha256sum --binary

# From Store::makeStorePath:
#
# string s = type + ":" + hash.to_string(Base16) + ":" + storeDir + ":" + name;
#
hash=$(nix-hash --type sha256 myfile)
s="source:sha256:$hash:/nix/store:myfile"
echo "s=[[$s]]"
echo -n "$s" >myfile.source
nix-hash --type sha256 --truncate --base32 --flat myfile.source

# Emulate nix-prefetch hash.
nix-prefetch-url file://<(echo hello)
nix-hash --type sha256 --flat --base32 <(echo hello)
