#!/usr/bin/env bash

set -euo pipefail

for file in *.nix; do
  if [[ $file == 'psmisc-fn-drv-2.nix' ]]; then
    # Supply required argument.
    nix-instantiate --arg foo true "$file"
  else
    nix-instantiate "$file"
  fi
done
