#!/usr/bin/env bash

set -euo pipefail

nix-build ./docker.nix -A docker
mkdir -p .cache
./result | docker load | tee .cache/docker.load.out
sed -e 's/Loaded image: //' <.cache/docker.load.out >.cache/docker-image.txt
