#!/usr/bin/env bash

set -euo pipefail

# WARNING: Many impurities used such as /usr/bin/* and /bin/*.

echo Arguments: "$@"
echo
echo 'Some Nix variables: {'
echo "  NIX_BUILD_TOP=${NIX_BUILD_TOP}"
echo "  TMP=${TMP}"
echo "  TMPDIR=${TMPDIR}"
echo "  PATH=${PATH}"
echo "  HOME=${HOME}"
echo "  NIX_STORE=${NIX_STORE}"
echo '}'

echo
echo 'Env vars from derivation {'
# shellcheck disable=SC2154
echo "  name=${name}"
# shellcheck disable=SC2154
echo "  builder=${builder}"
# shellcheck disable=SC2154
echo "  system=${system}"
# shellcheck disable=SC2154
echo "  out=${out}"
echo '}'

echo
echo 'Environment: {'
env | sort | sed -e 's/^/  /'
echo '}'

d="${out}/bin"
mkdir -p "${d}"
foo="${d}/foo"
cat >"${foo}" <<!
#!/bin/sh

echo Hello
!
chmod +x "${foo}"
