#!/usr/bin/env bash

set -euo pipefail

pkg=$1; shift
command=("${@}")

channels=(
  aardvark
  baboon
  caterpillar
  dingo
  emu
  flounder
  gorilla
  hummingbird
  impala
  koi
)

function run {
  channel=$1
  nix run -f channels.nix "${channel}.${pkg}" -c "${command[@]}" || true
}

for channel in "${channels[@]}"; do
  echo -----------------------------------
  echo "channel = ${channel}"
  echo -----------------------------------
  run "${channel}"
  echo -----------------------------------
  echo
done
