#!/usr/bin/env bash

set -euo pipefail

echo 'graph test { a -- b }' | ./result-flakes/graphviz/bin/dot -Tpng -o test1.png
~/.iterm2/imgcat test1.png

echo 'graph test { a -- b }' | ./result-flakes/graphvizCore/bin/dot -Tpng -o test2.png || true

./result-flakes/hello/bin/hello
./result-3/bin/hello
