#!/bin/sh

echo pkgs
nix-instantiate --eval --strict --json --attr pkgs | jq

echo
echo pkgs-fix
nix-instantiate --eval --strict --json --attr pkgs-fix | jq

echo
echo newpkgs
nix-instantiate --eval --strict --json --attr newpkgs | jq

echo
echo newpkgs2
nix-instantiate --eval --strict --json --attr newpkgs2 | jq
