#!/bin/sh

get_attrs() {
  nix-instantiate --eval \
      --expr 'builtins.attrNames (import ./default.nix)' --json |
    jq -r '.[]'
}

attrs=$(get_attrs)

for attr in $attrs; do
  echo
  echo "$attr:"
  nix-instantiate --eval --strict --json --attr "$attr" | jq
done
