#!/bin/sh

set -e
set -u

# shellcheck disable=SC2154
NIX_OUT=$out
# shellcheck disable=SC2154
NIX_BUILDER=$builder

echo "args = $*"

# shellcheck disable=SC2154
for arg in "$@"; do
  echo "arg = [[$arg]]"
done

echo "PWD = $PWD"
echo "pwd = $(pwd)"
echo "builder = $NIX_BUILDER"
echo "v1 = [[$V1]]"
echo "v2 = [[$V2]]"
echo "v3 = [[$V3]]"
echo "v4 = [[$V4]]"
echo "v5 = [[$V5]]"
echo "v6 = [[$V6]]"
echo "v7 = [[$V7]]"
echo "v8 = [[$V8]]"

# if not in a sandbox:
if [ -x /usr/bin/env ]; then
  echo "env {"
  /usr/bin/env | /usr/bin/sort | /usr/bin/sed 's/^/  /'
  echo "}"
fi

echo Generating "Hi!"
echo "Hi!" >"$NIX_OUT"
